[package]
name = "tg_gateway"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
teloxide = { version = "0.12", features = ["macros", "auto-send"] }
tg_core = { version = "0.1.0", path = "../core" }
thiserror = "2.0.12"
tokio = { version = "1.44.2", features = ["rt-multi-thread", "macros"] }
dotenvy = "0.15"
reqwest  = { version = "0.11", default-features = false, features = ["rustls-tls"] }